# Site settings
title: "Igloo's Bazaar"
email: igloosarecool@me.com
description: Tijd om mijn garage eens op te ruimen.
baseurl: "/bazaar" # the subpath of your site, e.g. /blog/
url: https://bart.debunne.be # the base hostname & protocol for your site
twitter_username: igloosarecool
github_username:  igloosarecool

# Build settings
markdown: kramdown
collections:
  products:
    output: true
sass:
  sass_dir: _sass
  style: compressed
  
# text labels and placeholders
text:
  contact:
    email:    'jouw@emailadres.com'
    content:  'jouw bericht'
    subject:  'Nieuw bericht van de Bazaar'
    submit:   'Verzenden'
    ajax:
      sending:  'Bezig ...'
      sent:     'Bericht verzonden!'
      error:    'Fout!'
  categories: [vintage,onderdelen,kledij]

# images source
src: "https://dl.dropboxusercontent.com/u/54388277/cdn/images/"